Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Controllers/SemesterController.cs
using System;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using MyStik.TimeTable.Data;
using MyStik.TimeTable.Web.Controllers;
using MyStik.TimeTable.Web.Models;

namespace MyStik.TimeTable.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class SemesterController : BaseController
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model = Db.Semesters.OrderByDescending(x => x.StartCourses).ToList();
            return View(model);
        }

        /// <summary>
        /// Ein Semester anlegen
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var model = new SemesterCreateViewModel();


            if (DateTime.Today.Month >= 3 && DateTime.Today.Month < 10)
            {
                var date = new DateTime(DateTime.Today.Year, 10, 1);
                // heute liegt im SS => das nächste ist das WS
                model.Name = string.Format("WS{0}", DateTime.Today.Year - 2000);
                model.StartCourses = date.Date.ToShortDateString();
                model.EndCourses = date.AddDays(100).Date.ToShortDateString();
            }
            else
            {
                // offenbar im WS => das nächste ist das SS
                if (DateTime.Today.Month < 3) // "dieses Jahr"
                {
                    model.Name = string.Format("SS{0}", DateTime.Today.Year - 2000);
                }
                else
                {
                    // nächstes Jahr
                    model.Name = string.Format("SS{0}", DateTime.Today.Year - 1999);
                }
                var date = new DateTime(DateTime.Today.Year, 3, 15);
                model.StartCourses = date.Date.ToShortDateString();
                model.EndCourses = date.AddDays(100).Date.ToShortDateString();
            }

            var culture = Thread.CurrentThread.CurrentUICulture;
            ViewBag.Culture = culture;

            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(SemesterCreateViewModel model)
        {
            // Vorbedingungen geprüft
            if (!ModelState.IsValid)
                return View(model);

            var from = DateTime.Parse(model.StartCourses);
            var to = DateTime.Parse(model.EndCourses);


            if (from >= to)
            {
                ModelState.AddModelError("StartCourses", "Vorlesungsbeginn liegt später als Vorlesungsende");
                ModelState.AddModelError("EndCourses", "Vorlesungsende liegt früher als Vorlesungsbeginn");
            }

            var semExists = Db.Semesters.Any(s => s.Name.ToUpper().Equals(model.Name.ToUpper()));
            if (semExists)
            {
                ModelState.AddModelError("Name", "Ein Semester mit diesem Namen existiert bereits");
            }

            /*
            semExists = Db.Semesters.SingleOrDefault(s => s.EndCourses >= from);
            if (semExists != null)
            {
                ModelState.AddModelError("StartCourses",
                    string.Format("Überschneidung mit Vorlesungsende von Semester {0}: {1}", semExists.Name,
                        semExists.EndCourses));
            }
            */

            // Nachbedingunen geprüft
            if (ModelState.IsValid)
            {
                // wenn alles ok, dann einen Redirect auf Index
                var sem = Db.Semesters.Add(new Semester
                {
                    Name = model.Name,
                    StartCourses = from,
                    EndCourses = to,
                });
                Db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(Guid id)
        {
            var model = Db.Semesters.SingleOrDefault(s => s.Id == id);

            return View(model);
        }

        /// <summary>
        /// Semester verändern
        /// </summary>
        /// <param name="id">SemesterId</param>
        /// <returns></returns>
        public ActionResult Edit(Guid id)
        {
            var model = new SemesterEditViewModel();

            var semester = Db.Semesters.SingleOrDefault(s => s.Id == id);

            model.SemesterId = semester.Id;
            model.Name = semester.Name;
            model.StartCourses = semester.StartCourses.ToShortDateString();
            model.EndCourses = semester.EndCourses.ToShortDateString();


            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(SemesterEditViewModel model)
        {
            var semester = Db.Semesters.SingleOrDefault(s => s.Id == model.SemesterId);

            semester.Name = model.Name;
            semester.StartCourses = DateTime.Parse(model.StartCourses);
            semester.EndCourses = DateTime.Parse(model.EndCourses);

            Db.SaveChanges();


            return RedirectToAction("Details", new { id = semester.Id });
        }

        /// <summary>
        /// Ein Semesterdatum anlegen
        /// </summary>
        /// <param name="id">SemesterId</param>
        /// <returns></returns>
        public ActionResult CreateDate(Guid id)
        {
            var semester = Db.Semesters.SingleOrDefault(s => s.Id == id);

            var model = new SemesterDateViewModel
            {
                SemesterId = semester.Id,
                //Start = semester.StartCourses.Date.ToShortDateString(),
                Start = DateTime.Today.ToShortDateString(),
                //End = semester.StartCourses.Date.ToShortDateString(),
                End = DateTime.Today.ToShortDateString(),
                HasCourses = false
            };

            ViewBag.Semester = semester;

            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateDate(SemesterDateViewModel model)
        {
            var semester = Db.Semesters.SingleOrDefault(s => s.Id == model.SemesterId);



            var semDate = new SemesterDate
            {
                Description = model.Description,
                From = DateTime.Parse(model.Start),
                To = DateTime.Parse(model.End),
                HasCourses = model.HasCourses,
                Semester = semester,

            };

            semester.Dates.Add(semDate);

            Db.SemesterDates.Add(semDate);
            Db.SaveChanges();



            return RedirectToAction("Details", new { id = semester.Id });
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">Id des Datums, dessen Attributwerte verändert werden solllen</param>
        /// <returns></returns>
        public ActionResult EditDate(Guid id)
        {
            var date = Db.SemesterDates.SingleOrDefault(s => s.Id == id);
            var semester = Db.Semesters.SingleOrDefault(s => s.Dates.Any(d => d.Id == id));

            var model = new SemesterDateViewModel
            {
                DateId = date.Id,
                SemesterId = semester.Id,
                Start = date.From.ToShortDateString(),
                End = date.To.ToShortDateString(),
                Description = date.Description,
                HasCourses = date.HasCourses
            };

            ViewBag.Semester = semester;

            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditDate(SemesterDateViewModel model)
        {
            // wir müssen uns hier wieder das Objekt aus der Datenbank holen
            // Dazu brauchen wir die Id
            // Daher mmüssen wir die Id schon vorher an das Formular übergeben
            var date = Db.SemesterDates.SingleOrDefault(s => s.Id == model.DateId);
            var semester = Db.Semesters.SingleOrDefault(s => s.Dates.Any(d => d.Id == model.DateId));

            // Jetzt aktualisieren wir die Attributwerte des Objekts aus der Datenbank
            // mit den Attributwerten aus dem Formular
            date.Description = model.Description;
            date.From = DateTime.Parse(model.Start);
            date.To = DateTime.Parse(model.End);
            date.HasCourses = model.HasCourses;
            // Reparatur
            if (date.Semester == null)
            {
                date.Semester = semester;
            }

            // Objekt wurde geändert
            // Jetzt speichern wir es in der Datenbank
            Db.SaveChanges();


            return RedirectToAction("Details", new { id = date.Semester.Id });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteDate(Guid id)
        {
            var date = Db.SemesterDates.SingleOrDefault(d => d.Id.Equals(id));

            var semester = date.Semester;

            if (semester != null)
            {
                semester.Dates.Remove(date);
            }

            Db.SemesterDates.Remove(date);

            Db.SaveChanges();

            return RedirectToAction("Details", new { id = semester.Id });
        }




        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/Create.cshtml
@model MyStik.TimeTable.Web.Models.SemesterCreateViewModel
@{
    ViewBag.Title = "Semester anlegen";
}
@section styles
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css")" />
}

<div class="page-header">
    <h1>
        Neues Semester anlegen
    </h1>
</div>


<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Neues Semester anlegen</h4>
            </div>
            <div class="panel-body">

                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.LabelFor(m => m.Name, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-8">
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Name)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StartCourses, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(model => model.StartCourses, new { @class = "form-control datepicker" })

                                @Html.ValidationMessageFor(m => m.StartCourses)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.EndCourses, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(model => model.EndCourses, new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(m => m.EndCourses)
                            </div>
                        </div>





                        <div class="form-group">
                            <div class="col-md-offset-4 col-md-10">
                                <input type="submit" value="anlegen" class="btn btn-default"/>
                            </div>
                        </div>
                    </fieldset>
                }

            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript" src="@Url.Content("~/Assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Assets/libs/bootstrap-datepicker/locales/bootstrap-datepicker.de.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Assets/fillter/scripts/datepicker.js")"></script>

    <script>

        $(function() {
            initDatePicker("datepicker", "@ViewBag.Culture.DateTimeFormat.ShortDatePattern", "@ViewBag.Culture.Name");
        });

    </script>
}

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/CreateDate.cshtml
@model MyStik.TimeTable.Web.Models.SemesterDateViewModel
@{
    ViewBag.Title = "Datum anlegen";
}
@section styles
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css")" />
}


<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Neuen Termin im Semester @ViewBag.Semester.Name anlegen</h4>
            </div>
            <div class="panel-body">

                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(m => m.SemesterId)

                        <div class="form-group">
                            @Html.LabelFor(m => m.Description, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-8">
                                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Description)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Start, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-2">
                                @Html.TextBoxFor(model => model.Start, new { @class = "form-control datepicker" })

                                @Html.ValidationMessageFor(m => m.Start)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.End, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-2">
                                @Html.TextBoxFor(model => model.End, new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(m => m.End)
                            </div>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.HasCourses)

                            <label for="HasCourses">Vorlesungszeit</label>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.Wichtig)

                            <label for="Wichtig">Ist wichtig</label>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.Eintaegig)

                            <label for="Eintaegig">Eintaegig</label>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.Terminstehtnochnichtfest)

                            <label for="Terminstehtnochnichtfest">Termin steht noch nicht fest</label>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-4 col-md-10">
                                <input type="submit" value="anlegen" class="btn btn-success"/>
                            </div>
                        </div>
                    </fieldset>
                }

            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript" src="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.de.min.js")"></script>

    <script>

        $(function () {
       
            $('.datepicker').datepicker({
                orientation: "left",
                autoclose: true,
                format: "dd.mm.yyyy",
                weekStart: 1,
                calendarWeeks: true,
                language: "de"
            });
        });

    </script>
}

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/Delete.cshtml
@model MyStik.TimeTable.Data.Semester
@{
    ViewBag.Title = "Delete";
}

<h2>Semester @Model.Name löschen</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Soll das Semester @Model.Name gelöscht werden?</h4>
    </div>
    <div class="panel-body">
        @Html.ActionLink("Ja", "DeleteConfirmed", "Semester", new { id = Model.Name }, new { @class="btn btn-danger"} )
        @Html.ActionLink("Nein", "Index", "Semester", null, new { @class = "btn btn-default" })
    </div>
</div>

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/Details.cshtml
@using MyStik.TimeTable.Web.Helpers
@model MyStik.TimeTable.Data.Semester

@{
    ViewBag.Title = "Zeitplan";
}

<div class="panel panel-default">
    <div class="panel-body bg-fillter-study">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h1>Detailinformationen zu Semester @Model.Name</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    Vorlesungszeit von @Model.StartCourses.Date.ToShortDateString() bis @Model.EndCourses.Date.ToShortDateString()
                    @Html.ActionButton("fa-cogs", "Einstellungen", "Edit", "Semester", new { id = Model.Id }, new { @class = "btn btn-default" })
                    @Html.ActionButton("fa-plus", "Neuer Termin", "CreateDate", "Semester", new { id = Model.Id }, new { @class = "btn btn-default" })

                </h4>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Zeitraum</th>
                        <th>Ebene</th>
                        <th>Art</th>
                        <th>Bezeichnung</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.Dates.OrderBy(x=>x.From))
                {
                    <tr>
                        <td>@Html.TimeSpan(item)</td>
                        @if (item.Organiser == null)
                        {
                            <td>hochschulweit</td>
                        }
                        else
                        {
                            <td>@item.Organiser.ShortName</td>
                        }
                        @if (item.HasCourses == false)
                        {
                            <td> <i>(Vorlesungsfrei)</i></td>
                        }
                        else
                        {
                            <td>mit Lehrveranstaltungen</td>
                        }
                        <td>@item.Description</td>
                        <td>
                            @Html.ActionButton("fa-pencil text-danger", "bearbeiten", "EditDate", "Semester", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
                            @Html.ActionButton("fa-trash-o text-danger", "löschen", "DeleteDate", "Semester", new { id = item.Id }, new { @class = "btn btn-default btn-xs text-danger" })
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/Edit.cshtml
@model MyStik.TimeTable.Web.Models.SemesterEditViewModel
@{
    ViewBag.Title = "Semester ändern";
}
@section styles
{
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css")" />
}


<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Semester ändern</h4>
            </div>
            <div class="panel-body">

                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(m => m.SemesterId)
                        <div class="form-group">
                            @Html.LabelFor(m => m.Name, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-8">
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Name)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StartCourses, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(model => model.StartCourses, new { @class = "form-control datepicker" })

                                @Html.ValidationMessageFor(m => m.StartCourses)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.EndCourses, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(model => model.EndCourses, new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(m => m.EndCourses)
                            </div>
                        </div>





                        <div class="form-group">
                            <div class="col-md-offset-4 col-md-10">
                                <input type="submit" value="speichern" class="btn btn-default"/>
                            </div>
                        </div>
                    </fieldset>
                }

            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript" src="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.de.min.js")"></script>

    <script>

        $(function() {
            $('.datepicker').datepicker({
                orientation: "left",
                autoclose: true,
                format: "dd.mm.yyyy",
                weekStart: 1,
                calendarWeeks: true,
                language: "de"
            });
        });

    </script>
}

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/EditDate.cshtml
@model MyStik.TimeTable.Web.Models.SemesterDateViewModel
@{
    ViewBag.Title = "Termin bearbeiten";
}
@section styles
{
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css")" />
}


<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Termin im Semester @ViewBag.Semester.Name bearbeiten</h4>
            </div>
            <div class="panel-body">

                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(m => m.SemesterId)
                        @Html.HiddenFor(m => m.DateId)


                        <div class="form-group">
                            @Html.LabelFor(m => m.Description, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-8">
                                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Description)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Start, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-2">
                                @Html.TextBoxFor(model => model.Start, new { @class = "form-control datepicker" })

                                @Html.ValidationMessageFor(m => m.Start)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.End, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-2">
                                @Html.TextBoxFor(model => model.End, new { @class = "form-control datepicker" })
                                @Html.ValidationMessageFor(m => m.End)
                            </div>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.HasCourses)

                            <label for="HasCourses">Vorlesungszeit</label>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.Wichtig)

                            <label for="Wichtig">Ist wichtig</label>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.Eintaegig)

                            <label for="Eintaegig">Eintaegig</label>
                        </div>

                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.Terminstehtnochnichtfest)

                            <label for="Terminstehtnochnichtfest">Termin steht noch nicht fest</label>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-4 col-md-10">
                                <input type="submit" value="übernehmen" class="btn btn-success"/>
                            </div>
                        </div>
                    </fieldset>
                }

            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript" src="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Assets/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.de.min.js")"></script>

    <script>

        $(function () {
       
            $('.datepicker').datepicker({
                orientation: "left",
                autoclose: true,
                format: "dd.mm.yyyy",
                weekStart: 1,
                calendarWeeks: true,
                language: "de"
            });
        });

    </script>
}

Sources/TimeTable/MyStik.TimeTable.Web/Areas/Admin/Views/Semester/Index.cshtml
@using MyStik.TimeTable.Web.Helpers
@model ICollection<MyStik.TimeTable.Data.Semester>

@{
    ViewBag.Title = "Index";
}
<div class="page-header">
    <h1>
        Semester <small>Vorlesungszeiten</small>
    </h1>
</div>



<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="@Url.Action("Create")" class="btn btn-primary"><i class="fa fa-plus"></i> Hinzufügen</a>
            </div>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Vorlesungsbeginn</th>
                        <th>Vorlesungsende</th>
                        <th>Vorlesungsfreie Zeiten</th>
                        <th>Semestergruppen</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var org in Model)
                    {
                        <tr>
                            <td><a href="@Url.Action("Details", new {id = org.Id})">@org.Name</a></td>
                            <td>@org.StartCourses</td>
                            <td>@org.EndCourses</td>
                            <td>
                                @foreach (var date in org.Dates.Where(x => x.Organiser == null))
                                {
                                    <div>@Html.TimeSpan(date): @date.Description</div>
                                }
                            </td>
                            <td>@org.Groups.Count</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>